name: D3
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2026.3.19
  - ld_impl_linux-64=2.44
  - libexpat=2.7.5
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.6
  - packaging=26.0
  - pip=26.0.1
  - pthread-stubs=0.3
  - python=3.10.20
  - readline=8.3
  - sqlite=3.51.2
  - tk=8.6.15
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.8.2
  - zlib=1.3.1
  - pip:
      - annotated-doc==0.0.4
      - anyio==4.13.0
      - certifi==2026.2.25
      - click==8.3.2
      - git+https://github.com/openai/CLIP.git
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.1
      - filelock==3.25.2
      - fsspec==2026.2.0
      - ftfy==6.3.1
      - h11==0.16.0
      - hf-xet==1.4.3
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.10.1
      - idna==3.11
      - imageio==2.37.3
      - jinja2==3.1.6
      - joblib==1.5.3
      - lazy-loader==0.5
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - opencv-python-headless==4.13.0.92
      - openpyxl==3.1.5
      - pandas==2.3.3
      - pillow==12.1.1
      - protobuf==7.34.1
      - pygments==2.20.0
      - python-dateutil==2.9.0.post0
      - pytz==2026.1.post1
      - pyyaml==6.0.3
      - regex==2026.4.4
      - rich==14.3.3
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - setuptools==69.5.1
      - shellingham==1.5.4
      - six==1.17.0
      - sympy==1.13.1
      - tensorboardx==2.6.5
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==0.6.13
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.3
      - triton==3.2.0
      - typer==0.24.1
      - typing-extensions==4.15.0
      - tzdata==2026.1
      - wcwidth==0.6.0



